/**
 * License Validation Service
 * Handles license key validation, storage, and verification
 *
 * Security Features:
 * - Keys stored as SHA-256 hashes (never plaintext in code)
 * - License file encrypted with AES-256-CBC
 * - Machine ID generation for optional binding
 */
const crypto = require('crypto');
const fs = require('fs');
const path = require('path');

// Salt for hashing - MUST match the one used in generate-keys.js
const SALT = 'INTERVIEW_ASSIST_2024_SECURE_SALT_v1';

// Encryption key derivation salt (different from hash salt)
const ENCRYPTION_SALT = 'LICENSE_ENCRYPT_SALT_v1';

// License file name
const LICENSE_FILE_NAME = 'license.dat';

// Hardcoded SHA-256 hashes of valid license keys
// Generated by scripts/generate-keys.js
const VALID_KEY_HASHES = [
    '9e329a98c848cd06ff8f9291abe413c1f0f7c125630f8e869b92ac82b7aa4cf9',
    '1c2b82c70c6b82ad72aba2ff387c42ed693dc9349aa8c1adce79911cffba096c',
    'd1fd642afb0378dc9c7eed47745b57cb6b1a5e51b9d69d69a2905d05e1559748',
    '2051659527528af7c2a4a9ea0be4e07638748387d698e9426c88fc50c7e31989',
    'e0ae6fd4d4c5f5e03a2a6c0f4035268790e3a1e322630718fc4e9a3dcb518989',
    '40c358d062ef191b7af5dfa441528e1dcbeeb0e95145eec1580803104cbfe66b',
    'd0c6d7111cbb622425c99a5044a2653d8c700f6245014abd6493ad2093ffa6b0',
    '93ebd90d033c77285c40cf17801d7f3cded7825eab8e2f3bc0409b3444c58476',
    '9bb928ca6b1cd394ea3c86ac5c15b3bb5e85e5d00b453699ddbaa640a5e9b15a',
    '293d047fd889479343242e7cfbb1f32d97bc4287c78ee17ab35b1557f26e2277',
    '0929662855a3da63d405eba943dfbffe9fbae42fa7f84b0550bf4a317362ced4',
    '8f3157d02fa5ecf15ce7ba168236d01413f6ff81bc52ba975cf31a8f3dc624d5',
    '9eefda7a7db7729a3d9fe99a7ca456f3af5b466558423541a54851a3c4ce7ab4',
    '3454f0074a0fd0b1ab68fa78f7fd641cded63cbd5d75117c1852ffc42fdaa9ae',
    '5f158dc0db59890a24c82472173dd577158b3e2eca0b03bab662e61a02ab53e1',
    'a6aeba92491fa0cf4a1c172955630db14ed49f61a5a168662e3773bce4fecf2f',
    '9169296e91dc1c95822d93bfb63164ecd1b6fc8462e7744da8af493cfc8912ae',
    '8c6657ae614e75fa1e5953f362cbd5ec1f840cf7f8783e2282afac61db28db88',
    '450031226c6d43b40fe0c51c9f570f5ecc0cccbb51a8c091fc2b2be1424e5581',
    '2b1f82799ec69cf3ee546d7d9264ea17f798d30559fb9db042da863284779d50',
    '099bbd822a6d126ddd192c2b610bfb61e9583f470694af9364b9b38f12ff2585',
    '4a973a88bd12d9a2bc108d5d52d79645341648ce081f76e5a30fb95b4dc2254c',
    '5548d3da50c90f695141384867888a14ba8ea8c1235d07d12c9c8fc28b36f4c1',
    'f2ab82abdfac3ed86c74bbf7038792bc90d2efe81eeeb5ede9f1a035fcf2f9fc',
    '217f0884727ca35e5575bc2958d9f9397ec6c2f3bcf2aa82050c72053bdd2a5d',
    'f99e8fb50c687eca707bbf10758c463d76ef418f60057a39746cc609d318c84d',
    'ebb2b20d29f398da25880f9f712147dcdcde139fe852d77fff35df897b08977c',
    '75b9c1ccbe0fa5ae0e3b6579573bdfe1cd9d571a1a72060b912d479f3fa1b8e5',
    '94e975847390ce9fc75db9566f9748928d3f94d9f2eaca52a24e7e9ff17e1b97',
    '918d230b505c551480ac81dc3f750d47336e6a05be58beaa53d4cf44f4a85c3f'
];

class LicenseService {
    constructor() {
        this.licenseDir = null;
        this.licensePath = null;
        this.isActivated = false;
        this.activatedKeyHash = null;
        this.activationDate = null;
    }

    /**
     * Initialize the license service with the user data path
     * @param {string} userDataPath Path to Electron userData directory
     */
    initialize(userDataPath) {
        this.licenseDir = userDataPath;
        this.licensePath = path.join(userDataPath, LICENSE_FILE_NAME);
    }

    /**
     * Hash a license key using SHA-256 + salt
     * @param {string} plainKey Plain text license key
     * @returns {string} SHA-256 hash
     */
    hashKey(plainKey) {
        // Normalize: uppercase, remove all non-alphanumeric except dashes
        const normalized = plainKey.toUpperCase().trim();
        return crypto.createHash('sha256').update(normalized + SALT).digest('hex');
    }

    /**
     * Validate license key format
     * @param {string} key License key to validate
     * @returns {boolean} True if format is valid
     */
    validateKeyFormat(key) {
        // Format: XXXX-XXXX-XXXX-XXXX (alphanumeric, no 0/O/1/I)
        const pattern = /^[A-HJ-NP-Z2-9]{4}-[A-HJ-NP-Z2-9]{4}-[A-HJ-NP-Z2-9]{4}-[A-HJ-NP-Z2-9]{4}$/i;
        return pattern.test(key.trim());
    }

    /**
     * Check if a license key is valid
     * @param {string} plainKey Plain text license key
     * @returns {boolean} True if key is valid
     */
    isValidKey(plainKey) {
        if (!this.validateKeyFormat(plainKey)) {
            return false;
        }
        const hash = this.hashKey(plainKey);
        return VALID_KEY_HASHES.includes(hash);
    }

    /**
     * Encrypt data for secure storage
     * @param {object} data Data to encrypt
     * @returns {object} Encrypted data with IV
     */
    encryptForStorage(data) {
        const key = crypto.scryptSync(ENCRYPTION_SALT, 'salt', 32);
        const iv = crypto.randomBytes(16);
        const cipher = crypto.createCipheriv('aes-256-cbc', key, iv);
        let encrypted = cipher.update(JSON.stringify(data), 'utf8', 'hex');
        encrypted += cipher.final('hex');
        return {
            iv: iv.toString('hex'),
            data: encrypted,
            version: 1
        };
    }

    /**
     * Decrypt data from storage
     * @param {object} encrypted Encrypted data object
     * @returns {object|null} Decrypted data or null if failed
     */
    decryptFromStorage(encrypted) {
        try {
            const key = crypto.scryptSync(ENCRYPTION_SALT, 'salt', 32);
            const iv = Buffer.from(encrypted.iv, 'hex');
            const decipher = crypto.createDecipheriv('aes-256-cbc', key, iv);
            let decrypted = decipher.update(encrypted.data, 'hex', 'utf8');
            decrypted += decipher.final('utf8');
            return JSON.parse(decrypted);
        } catch (error) {
            console.error('License decryption failed:', error.message);
            return null;
        }
    }

    /**
     * Generate a machine-specific ID
     * @returns {string} Machine ID hash
     */
    getMachineId() {
        const os = require('os');
        const data = [
            os.hostname(),
            os.platform(),
            os.arch(),
            os.cpus()[0]?.model || 'unknown'
        ].join('-');
        return crypto.createHash('md5').update(data).digest('hex').substring(0, 16);
    }

    /**
     * Activate a license key
     * @param {string} plainKey Plain text license key
     * @returns {object} Result with success status
     */
    async activateLicense(plainKey) {
        // Validate the key
        if (!this.validateKeyFormat(plainKey)) {
            return { success: false, error: 'Invalid key format. Expected: XXXX-XXXX-XXXX-XXXX' };
        }

        if (!this.isValidKey(plainKey)) {
            return { success: false, error: 'Invalid license key' };
        }

        // Create license data
        const licenseData = {
            keyHash: this.hashKey(plainKey),
            activatedAt: new Date().toISOString(),
            machineId: this.getMachineId(),
            appVersion: require('electron').app.getVersion()
        };

        // Encrypt and save
        const encrypted = this.encryptForStorage(licenseData);

        try {
            fs.writeFileSync(this.licensePath, JSON.stringify(encrypted, null, 2));
            this.isActivated = true;
            this.activatedKeyHash = licenseData.keyHash;
            this.activationDate = licenseData.activatedAt;
            return { success: true, activatedAt: licenseData.activatedAt };
        } catch (error) {
            console.error('Failed to save license:', error);
            return { success: false, error: 'Failed to save license file' };
        }
    }

    /**
     * Check for an existing valid license
     * @returns {object} License status
     */
    checkExistingLicense() {
        if (!this.licensePath) {
            return { valid: false, reason: 'not_initialized' };
        }

        if (!fs.existsSync(this.licensePath)) {
            return { valid: false, reason: 'no_license' };
        }

        try {
            const encryptedData = JSON.parse(fs.readFileSync(this.licensePath, 'utf8'));
            const licenseData = this.decryptFromStorage(encryptedData);

            if (!licenseData) {
                return { valid: false, reason: 'corrupted' };
            }

            // Verify the key hash is still valid
            if (!VALID_KEY_HASHES.includes(licenseData.keyHash)) {
                return { valid: false, reason: 'invalid_key' };
            }

            // Optional: Check machine binding (uncomment to enable)
            // if (licenseData.machineId !== this.getMachineId()) {
            //     return { valid: false, reason: 'machine_mismatch' };
            // }

            // License is valid
            this.isActivated = true;
            this.activatedKeyHash = licenseData.keyHash;
            this.activationDate = licenseData.activatedAt;

            return {
                valid: true,
                activatedAt: licenseData.activatedAt,
                machineId: licenseData.machineId
            };
        } catch (error) {
            console.error('License check error:', error);
            return { valid: false, reason: 'read_error' };
        }
    }

    /**
     * Deactivate the current license
     */
    deactivateLicense() {
        try {
            if (fs.existsSync(this.licensePath)) {
                fs.unlinkSync(this.licensePath);
            }
        } catch (error) {
            console.error('Failed to delete license file:', error);
        }
        this.isActivated = false;
        this.activatedKeyHash = null;
        this.activationDate = null;
    }

    /**
     * Get current license status
     * @returns {object} Current status
     */
    getStatus() {
        return {
            isActivated: this.isActivated,
            activationDate: this.activationDate,
            machineId: this.getMachineId()
        };
    }
}

// Export singleton instance
module.exports = new LicenseService();
