/**
 * License Validation Service
 * Handles license key validation, storage, and verification
 *
 * Security Features:
 * - Keys stored as SHA-256 hashes (never plaintext in code)
 * - License file encrypted with AES-256-CBC
 * - Machine ID generation for optional binding
 */
const crypto = require('crypto');
const fs = require('fs');
const path = require('path');

// Salt for hashing - MUST match the one used in generate-keys.js
const SALT = 'INTERVIEW_ASSIST_2024_SECURE_SALT_v1';

// Encryption key derivation salt (different from hash salt)
const ENCRYPTION_SALT = 'LICENSE_ENCRYPT_SALT_v1';

// License file name
const LICENSE_FILE_NAME = 'license.dat';

// Hardcoded SHA-256 hashes of valid license keys
// Generated by scripts/generate-keys.js
const VALID_KEY_HASHES = [
    'e1fec45c0f3d69b8a7b593e5daea2957194ca25e4408f542312a592b19f6f459',
    'd3e7dfb86c6d114dd9b05045c329fe002aa924107359e22d9d9ef612b91cab0a',
    '6d629c33e06aa904f01738815a871bc3fad1eb5ad1deb5105d1624577aabfd62',
    '81f3ba6ed4d18f47242495117eedcdaded7c4cf8928e7a9bc05e811821980b23',
    '008884242ddd001b0e6ab4a07669c3de979655e69dc3c712a75a6f743fbb97dd',
    '482604b227fe3e6171caea3c2c3d5304d1f53aa5587cdd4e77c874f55e4cf26e',
    '91ae51edd985b5b7d5ea795847b845b2495af34c2a4778ac965bb870ff245932',
    '5d87a8e399048dafc30432fcff8ddeaa6da8d3608de5361467edce52eb049588',
    'cf45f6573f70cb6da3f01a29e50955dee9b07045976a36e2c256b94b44e5b050',
    '84fe45924e7ee2a880fcccb81b05e7b62b96ebd15f2112c1036f6f5f140de8b7',
    'a2d9bde2456598459f2d3309589ff84f19e249819512b40d6e4fc500f1554b6b',
    '45fbbe1bd96ffe51a52568f70738fc15be9edeefa3257cfb390f04bfcf4ed45b',
    '2effc570f7e433e32206b59e2937c39be8bdca02e00e33d57640cc3b746c5305',
    '9cb176b527c460da70f686ffdf2d1d65191737266038919630a04c945be7bb73',
    '1dc578820b9c763276abf15a276dd70e3f2221801d2c966d8b34bbc72d6b8249',
    '90395cf7b34ff2c4486c8dfd235244bac8c997bcc0899a74a56608c811f89829',
    '294f8f871a41f88a1a06993a0736858afba753962f9ec5d0b6df113347fa9b29',
    '207a0d5cdcec6754033567daee769dd6658553fc1ce33ba43ac4175f9fb2be97',
    '7beb11cdc41b5e0e42a0f4dcd2183d2b20d03cdcd56407b6087c2c2abca76789',
    '808cc1d0ba2ad235e04efb7d8b1c2fcd253cfebfeb62a3329d31e69b2a005a45',
    'dce0714ea26926e757cfd3dccb1fb34e552cbedab37e637691906dc349f34d34',
    '786ff69044c244035258516c7af081145c444cf3f3b8f28ab35940d6f77bb3b7',
    '67d9ba92c2b2da77d5fa6ddf55a8960bc7aaaee687d31afb56eef90f2f79d9c7',
    '929b8656bedbdd408a91b2e1e73815f9d5d8906a5f5a6e8db3a7ef8f0df02e89',
    '64a700baac2a008b5c6d02d50b617d40d4f5617cc0e0ca4c03a96f47139701d1',
    '7c827a68251f175770ce761a0a03f7e0e306de80a14c4482dabccac94be03cfb',
    '05c7cfc094152fc4f0032f91c15f4c1a31d1a90e2fac3d3ae6382e05a460e7cd',
    '4a74f19de078cf0e5a7b2d197db7612c4c3f1dfc9b71a104a3822caa9fc59595',
    '88ec5397559425bd00053e2f6993b0d349a1e9aaba18ea9a7a5e4e5402334eeb',
    '5467348634f8896445c4e00bbe5a9f1c79b7cd308ff6d0947ac55acd75fa5890'
];

class LicenseService {
    constructor() {
        this.licenseDir = null;
        this.licensePath = null;
        this.isActivated = false;
        this.activatedKeyHash = null;
        this.activationDate = null;
    }

    /**
     * Initialize the license service with the user data path
     * @param {string} userDataPath Path to Electron userData directory
     */
    initialize(userDataPath) {
        this.licenseDir = userDataPath;
        this.licensePath = path.join(userDataPath, LICENSE_FILE_NAME);
    }

    /**
     * Hash a license key using SHA-256 + salt
     * @param {string} plainKey Plain text license key
     * @returns {string} SHA-256 hash
     */
    hashKey(plainKey) {
        // Normalize: uppercase, remove all non-alphanumeric except dashes
        const normalized = plainKey.toUpperCase().trim();
        return crypto.createHash('sha256').update(normalized + SALT).digest('hex');
    }

    /**
     * Validate license key format
     * @param {string} key License key to validate
     * @returns {boolean} True if format is valid
     */
    validateKeyFormat(key) {
        // Format: XXXX-XXXX-XXXX-XXXX (alphanumeric, no 0/O/1/I)
        const pattern = /^[A-HJ-NP-Z2-9]{4}-[A-HJ-NP-Z2-9]{4}-[A-HJ-NP-Z2-9]{4}-[A-HJ-NP-Z2-9]{4}$/i;
        return pattern.test(key.trim());
    }

    /**
     * Check if a license key is valid
     * @param {string} plainKey Plain text license key
     * @returns {boolean} True if key is valid
     */
    isValidKey(plainKey) {
        if (!this.validateKeyFormat(plainKey)) {
            return false;
        }
        const hash = this.hashKey(plainKey);
        return VALID_KEY_HASHES.includes(hash);
    }

    /**
     * Encrypt data for secure storage
     * @param {object} data Data to encrypt
     * @returns {object} Encrypted data with IV
     */
    encryptForStorage(data) {
        const key = crypto.scryptSync(ENCRYPTION_SALT, 'salt', 32);
        const iv = crypto.randomBytes(16);
        const cipher = crypto.createCipheriv('aes-256-cbc', key, iv);
        let encrypted = cipher.update(JSON.stringify(data), 'utf8', 'hex');
        encrypted += cipher.final('hex');
        return {
            iv: iv.toString('hex'),
            data: encrypted,
            version: 1
        };
    }

    /**
     * Decrypt data from storage
     * @param {object} encrypted Encrypted data object
     * @returns {object|null} Decrypted data or null if failed
     */
    decryptFromStorage(encrypted) {
        try {
            const key = crypto.scryptSync(ENCRYPTION_SALT, 'salt', 32);
            const iv = Buffer.from(encrypted.iv, 'hex');
            const decipher = crypto.createDecipheriv('aes-256-cbc', key, iv);
            let decrypted = decipher.update(encrypted.data, 'hex', 'utf8');
            decrypted += decipher.final('utf8');
            return JSON.parse(decrypted);
        } catch (error) {
            console.error('License decryption failed:', error.message);
            return null;
        }
    }

    /**
     * Generate a machine-specific ID
     * @returns {string} Machine ID hash
     */
    getMachineId() {
        const os = require('os');
        const data = [
            os.hostname(),
            os.platform(),
            os.arch(),
            os.cpus()[0]?.model || 'unknown'
        ].join('-');
        return crypto.createHash('md5').update(data).digest('hex').substring(0, 16);
    }

    /**
     * Activate a license key
     * @param {string} plainKey Plain text license key
     * @returns {object} Result with success status
     */
    async activateLicense(plainKey) {
        // Validate the key
        if (!this.validateKeyFormat(plainKey)) {
            return { success: false, error: 'Invalid key format. Expected: XXXX-XXXX-XXXX-XXXX' };
        }

        if (!this.isValidKey(plainKey)) {
            return { success: false, error: 'Invalid license key' };
        }

        // Create license data
        const licenseData = {
            keyHash: this.hashKey(plainKey),
            activatedAt: new Date().toISOString(),
            machineId: this.getMachineId(),
            appVersion: require('electron').app.getVersion()
        };

        // Encrypt and save
        const encrypted = this.encryptForStorage(licenseData);

        try {
            fs.writeFileSync(this.licensePath, JSON.stringify(encrypted, null, 2));
            this.isActivated = true;
            this.activatedKeyHash = licenseData.keyHash;
            this.activationDate = licenseData.activatedAt;
            return { success: true, activatedAt: licenseData.activatedAt };
        } catch (error) {
            console.error('Failed to save license:', error);
            return { success: false, error: 'Failed to save license file' };
        }
    }

    /**
     * Check for an existing valid license
     * @returns {object} License status
     */
    checkExistingLicense() {
        if (!this.licensePath) {
            return { valid: false, reason: 'not_initialized' };
        }

        if (!fs.existsSync(this.licensePath)) {
            return { valid: false, reason: 'no_license' };
        }

        try {
            const encryptedData = JSON.parse(fs.readFileSync(this.licensePath, 'utf8'));
            const licenseData = this.decryptFromStorage(encryptedData);

            if (!licenseData) {
                return { valid: false, reason: 'corrupted' };
            }

            // Verify the key hash is still valid
            if (!VALID_KEY_HASHES.includes(licenseData.keyHash)) {
                return { valid: false, reason: 'invalid_key' };
            }

            // Optional: Check machine binding (uncomment to enable)
            // if (licenseData.machineId !== this.getMachineId()) {
            //     return { valid: false, reason: 'machine_mismatch' };
            // }

            // License is valid
            this.isActivated = true;
            this.activatedKeyHash = licenseData.keyHash;
            this.activationDate = licenseData.activatedAt;

            return {
                valid: true,
                activatedAt: licenseData.activatedAt,
                machineId: licenseData.machineId
            };
        } catch (error) {
            console.error('License check error:', error);
            return { valid: false, reason: 'read_error' };
        }
    }

    /**
     * Deactivate the current license
     */
    deactivateLicense() {
        try {
            if (fs.existsSync(this.licensePath)) {
                fs.unlinkSync(this.licensePath);
            }
        } catch (error) {
            console.error('Failed to delete license file:', error);
        }
        this.isActivated = false;
        this.activatedKeyHash = null;
        this.activationDate = null;
    }

    /**
     * Get current license status
     * @returns {object} Current status
     */
    getStatus() {
        return {
            isActivated: this.isActivated,
            activationDate: this.activationDate,
            machineId: this.getMachineId()
        };
    }
}

// Export singleton instance
module.exports = new LicenseService();
